### PR TITLE
Update keyboard layout and color for Mac (and dark mode)

### PR DESCRIPTION
**Pull request by quintusl**
I guess we may not need wxScrolledWindow for the keyboard layout UI. Maybe a wxPanel could fit the case.

### CODE REVIEW

**Comment by Arakula** [comment]
Since there's currently no benefit from using wxScrolledWindow, I included your wxPanel change.

The color handling, however ... I think I got an implementation that should work better in dark mode on macOS. I committed that one to my repository now; please try it. I depend on your input on this one.

**Comment by quintusl** [comment]
Thank you.

**Comment by quintusl** [comment]
The following compiler errors are encountred:
```
clang++ -mmacosx-version-min=10.14 -c `wx-config --cxxflags` -fpermissive `pkg-config libusb-1.0 --cflags` -o KbdWnd.o KbdWnd.cpp
KbdWnd.cpp:218:5: error: no matching function for call to 'DiffColour'
    DiffColour(clrKey[ksUnpressed][0],
    ^~~~~~~~~~
KbdWnd.cpp:168:17: note: candidate function not viable: expects an l-value for 2nd argument
static wxColour DiffColour
                ^
KbdWnd.cpp:222:5: error: no matching function for call to 'DiffColour'
    DiffColour(clrKey[ksUnpressed][0],
    ^~~~~~~~~~
KbdWnd.cpp:168:17: note: candidate function not viable: expects an l-value for 2nd argument
static wxColour DiffColour
                ^
KbdWnd.cpp:226:5: error: no matching function for call to 'DiffColour'
    DiffColour(clrKey[ksUnpressed][0],
    ^~~~~~~~~~
KbdWnd.cpp:168:17: note: candidate function not viable: expects an l-value for 2nd argument
static wxColour DiffColour
```

**Comment by quintusl** [comment]
This patch may fix it
```
diff --git a/KbdWnd.cpp b/KbdWnd.cpp
index 87de2eb..00c2325 100644
--- a/KbdWnd.cpp
+++ b/KbdWnd.cpp
@@ -167,9 +167,9 @@ wxEND_EVENT_TABLE()
 
 static wxColour DiffColour
     (
-    wxColour &unpressed,
-    wxColour &defUnpressed,
-    wxColour &defDiff
+    wxColour unpressed,
+    wxColour defUnpressed,
+    wxColour defDiff
     )
 {
 wxColour out;
```

**Comment by quintusl** [comment]
Yeah.. The dark theme color scheme is cool. !!!
Thanks very much.

https://imgur.com/Jn3AXM2

https://imgur.com/hktKhPo

**Comment by Arakula** [comment]
Thank you for reporting the compiler error (it's always funny to run into things that work on Microsoft Compilers but not on gcc/clang and the other way round...), and glad you like it!

**Pull request closed without merging**
